# Generated by Django 3.1.1 on 2020-10-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='razon_Social',
            new_name='razon_social',
        ),
    ]
